"""PK + cluster-stratified sampler for supervised contrastive training.

Standard "P classes x K samples per class" (PK) batching for contrastive
losses, with one twist: within each class's K samples, we round-robin
across sequence-identity clusters so the K samples are genuinely diverse.

Inputs come from `cipher.data.prepare_training_data` output:
    class_labels : list of primary K-type (or O-type) labels per training sample
    cluster_ids  : list of cluster ids (already joined via md5 -> cluster)
    P            : number of distinct classes per batch
    K            : number of samples per class per batch

Batches are generated by:
    1. Pick P classes uniformly from classes that have >= K samples total.
    2. Per chosen class, shuffle its clusters and round-robin through them
       taking 1 protein per cluster until K are collected.
    3. Flatten P * K indices -> one batch.

Classes with fewer than K samples (including after cluster deduplication,
if strict mode is used) are excluded from sampling.

Usage:
    from torch.utils.data import DataLoader
    sampler = PKClusterSampler(class_labels, cluster_ids, P=32, K=8,
                               num_batches_per_epoch=200, seed=42)
    # batch_size must be passed to DataLoader even though sampler yields
    # full batches of size P*K.
    loader = DataLoader(dataset, batch_sampler=sampler)
"""

from __future__ import annotations

from collections import defaultdict
from typing import Iterable, Iterator, List, Sequence

import numpy as np
from torch.utils.data import Sampler


class PKClusterSampler(Sampler[List[int]]):
    """Yield batches of P*K sample indices, class-balanced + cluster-stratified.

    Attributes
    ----------
    class_labels : Sequence
        length-N iterable of per-sample primary class labels (hashable).
    cluster_ids : Sequence, optional
        length-N iterable of per-sample cluster ids. When None, every sample
        is treated as its own singleton cluster (i.e. pure class-balanced PK
        sampling with no cluster stratification).
    P : int
        classes per batch.
    K : int
        samples per class per batch.
    num_batches_per_epoch : int, optional
        how many batches to yield per epoch. Defaults to
        ceil(n_usable_samples / (P*K)).
    seed : int
        RNG seed. The internal RNG is re-seeded per epoch to
        `seed + epoch`; call `.set_epoch(e)` between epochs for
        reproducibility with DDP / checkpointing.
    strict : bool
        if True, exclude classes with fewer than K distinct clusters (not
        just fewer than K samples). Encourages batch-level diversity but
        drops more classes. Default False.
    """

    def __init__(
        self,
        class_labels: Sequence,
        cluster_ids: Sequence | None,
        P: int,
        K: int,
        num_batches_per_epoch: int | None = None,
        seed: int = 0,
        strict: bool = False,
    ):
        if len(class_labels) == 0:
            raise ValueError('class_labels is empty')
        if cluster_ids is not None and len(cluster_ids) != len(class_labels):
            raise ValueError(
                f'class_labels ({len(class_labels)}) and cluster_ids '
                f'({len(cluster_ids)}) must have same length')
        if P <= 0 or K <= 0:
            raise ValueError(f'P and K must be positive, got P={P}, K={K}')

        self.P = P
        self.K = K
        self.seed = seed
        self.strict = strict
        self._epoch = 0

        # Group indices by class, and by (class, cluster)
        # class_to_clusters[c] = list of cluster_ids present for class c
        # class_cluster_to_idx[(c, cluster)] = list of sample indices
        class_to_indices: dict = defaultdict(list)
        class_cluster_to_idx: dict = defaultdict(list)
        class_to_clusters: dict = defaultdict(set)
        n = len(class_labels)
        for i in range(n):
            c = class_labels[i]
            cluster = cluster_ids[i] if cluster_ids is not None else i
            class_to_indices[c].append(i)
            class_cluster_to_idx[(c, cluster)].append(i)
            class_to_clusters[c].add(cluster)

        # Filter to usable classes: need >= K samples, and in strict mode,
        # >= K distinct clusters.
        usable = []
        for c, idx_list in class_to_indices.items():
            if len(idx_list) < K:
                continue
            if strict and len(class_to_clusters[c]) < K:
                continue
            usable.append(c)

        if len(usable) < P:
            raise ValueError(
                f'Only {len(usable)} usable classes (need >= K={K} samples '
                f'{"and >= K distinct clusters " if strict else ""}'
                f'each), but P={P} required. '
                f'Lower P, lower K, disable strict, or enlarge training set.')

        self._class_to_indices = {c: list(v) for c, v in class_to_indices.items()}
        self._class_cluster_to_idx = {k: list(v) for k, v in class_cluster_to_idx.items()}
        self._class_to_clusters = {c: list(v) for c, v in class_to_clusters.items()}
        self._usable_classes = list(usable)

        if num_batches_per_epoch is None:
            total_usable = sum(len(self._class_to_indices[c]) for c in usable)
            num_batches_per_epoch = max(1, total_usable // (P * K))
        self.num_batches_per_epoch = num_batches_per_epoch

    # ---- PyTorch Sampler interface ----

    def set_epoch(self, epoch: int) -> None:
        self._epoch = int(epoch)

    def __len__(self) -> int:
        return self.num_batches_per_epoch

    def __iter__(self) -> Iterator[List[int]]:
        rng = np.random.default_rng(self.seed + self._epoch)
        for _ in range(self.num_batches_per_epoch):
            yield self._sample_one_batch(rng)
        self._epoch += 1  # auto-advance so unset-epoch loops still vary

    # ---- internals ----

    def _sample_one_batch(self, rng: np.random.Generator) -> List[int]:
        chosen_classes = rng.choice(
            self._usable_classes, size=self.P, replace=False)

        batch: List[int] = []
        for c in chosen_classes:
            batch.extend(self._sample_class(c, rng))
        return batch

    def _sample_class(self, c, rng: np.random.Generator) -> List[int]:
        """Round-robin across this class's clusters until K samples drawn."""
        clusters = list(self._class_to_clusters[c])
        rng.shuffle(clusters)

        # Build per-cluster index queues (shuffled once per batch).
        cluster_queues: dict = {}
        for cluster in clusters:
            idxs = list(self._class_cluster_to_idx[(c, cluster)])
            rng.shuffle(idxs)
            cluster_queues[cluster] = idxs

        chosen: List[int] = []
        cursor = {cluster: 0 for cluster in clusters}
        while len(chosen) < self.K:
            advanced = False
            for cluster in clusters:
                if len(chosen) >= self.K:
                    break
                queue = cluster_queues[cluster]
                i = cursor[cluster]
                if i < len(queue):
                    chosen.append(queue[i])
                    cursor[cluster] = i + 1
                    advanced = True
            if not advanced:
                # Shouldn't happen if the class passes the usable filter,
                # but bail defensively rather than loop forever.
                break
        return chosen


def batch_class_distribution(batch_indices: Iterable[int],
                             class_labels: Sequence) -> dict:
    """Helper for tests / diagnostics: count classes in a batch."""
    counts: dict = defaultdict(int)
    for i in batch_indices:
        counts[class_labels[i]] += 1
    return dict(counts)
